name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure
    - name: make Filter/
      run: make Filter/
    - name: Filter/bin/filter -d Filter/bin/yard.bmp Filter/bin/dyard.bmp
      run: Filter/bin/filter -d Filter/bin/yard.bmp Filter/bin/dyard.bmp
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
